language: generic
addons:
  apt:
    packages:
      - oraclejdk8  # install Java8 as required by vnu.jar

sudo: enabled

branches:
  only:
    - master

install:
 - pip install html5validator

script: html5validator --root . --also-check-css
